name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve! Please fill out the following details.
  - type: input
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior (include code if possible).
      placeholder: |
        1. Load data '...'
        2. Run function '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: code_example
    attributes:
      label: Code Example
      description: Minimal reproducible example (R code)
      render: r
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, R version, package version, etc.
      placeholder: |
        - OS: macOS 12.1
        - R Version: 4.1.2
        - Package Version: 0.1.0
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here. 