blank_issues_enabled: false
contact_links:
  - name: 📋 Roadmap Implementation
    url: https://github.com/revgizmo/career-data-science/blob/main/STRATEGIC_ROADMAP_AND_ACTION_PLAN.md
    about: View the strategic roadmap and implementation plan
  - name: ✅ Active Checklist
    url: https://github.com/revgizmo/career-data-science/blob/main/ACTIVE_ROADMAP_CHECKLIST.md
    about: Track progress on the active roadmap checklist
  - name: 📊 Process Management
    url: https://github.com/revgizmo/career-data-science/blob/main/PROCESS_MANAGEMENT_GUIDE.md
    about: Learn about our process management approach