name: Documentation

# description is required for issue forms
description: Suggest improvements or report issues with documentation
title: '[DOCS] '
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        Please help us improve our documentation! Fill out the details below.
  - type: input
    id: doc_location
    attributes:
      label: Documentation Location
      description: Where is the documentation that needs to be updated? (e.g. README, function documentation, vignettes)
  - type: textarea
    id: current_doc
    attributes:
      label: Current Documentation
      description: What does the current documentation say?
  - type: textarea
    id: suggested_changes
    attributes:
      label: Suggested Changes
      description: What changes would you like to see?
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Is this blocking your use of the package? Are there related documentation issues? Any examples of good documentation you'd like to reference? 