#!/usr/bin/env Rscript

# Scope Reduction Implementation Script for Issue #393
# This script implements the massive scope reduction required for CRAN submission

cat("🔍 IMPLEMENTING SCOPE REDUCTION FOR ISSUE #393\n")
cat("=============================================\n\n")

# Load the package
devtools::load_all()

# Source the scope reduction implementation
source("R/scope_reduction_implementation.R")

cat("📊 CURRENT STATUS\n")
cat("-----------------\n")
summary <- get_scope_reduction_summary()
cat("Current functions:", summary$current_functions, "\n")
cat("Target functions:", summary$target_functions, "\n")
cat("Essential functions:", summary$essential_functions, "\n")
cat("Deprecated functions:", summary$deprecated_functions, "\n")
cat("Reduction needed:", summary$reduction_percentage, "%\n\n")

# Step 1: Add deprecation warnings to deprecated functions
cat("🚨 STEP 1: ADDING DEPRECATION WARNINGS\n")
cat("-------------------------------------\n")

# Function to add deprecation warning wrapper
add_deprecation_wrapper <- function(func_name) {
  # Get the original function
  original_func <- get(func_name, envir = asNamespace("engager"))
  
  # Create deprecation warning wrapper
  wrapper <- function(...) {
    warning(
      "Function '", func_name, "' is deprecated and will be removed in the next version. ",
      "Please use the essential functions instead. ",
      "See ?get_essential_functions for alternatives.",
      call. = FALSE
    )
    # Call the original function
    original_func(...)
  }
  
  # Copy attributes from original function
  attributes(wrapper) <- attributes(original_func)
  
  # Assign the wrapper back to the package namespace
  assign(func_name, wrapper, envir = asNamespace("engager"))
  
  cat("  ✓ Added deprecation warning to:", func_name, "\n")
}

# Add deprecation warnings to all deprecated functions
cat("Adding deprecation warnings to", length(DEPRECATED_FUNCTIONS), "functions...\n")
for (func_name in DEPRECATED_FUNCTIONS) {
  tryCatch({
    add_deprecation_wrapper(func_name)
  }, error = function(e) {
    cat("  ✗ Failed to add deprecation warning to:", func_name, "-", e$message, "\n")
  })
}

cat("\n✅ DEPRECATION WARNINGS ADDED\n\n")

# Step 2: Test that essential functions still work
cat("🧪 STEP 2: TESTING ESSENTIAL FUNCTIONS\n")
cat("-------------------------------------\n")

# Test essential functions
essential_test_results <- list()
for (func_name in ESSENTIAL_FUNCTIONS) {
  tryCatch({
    # Check if function exists and is callable
    func <- get(func_name, envir = asNamespace("engager"))
    if (is.function(func)) {
      essential_test_results[[func_name]] <- "OK"
      cat("  ✓", func_name, "- OK\n")
    } else {
      essential_test_results[[func_name]] <- "NOT_FUNCTION"
      cat("  ✗", func_name, "- NOT A FUNCTION\n")
    }
  }, error = function(e) {
    essential_test_results[[func_name]] <- paste("ERROR:", e$message)
    cat("  ✗", func_name, "- ERROR:", e$message, "\n")
  })
}

cat("\n✅ ESSENTIAL FUNCTIONS TESTED\n\n")

# Step 3: Test deprecated functions still work but show warnings
cat("⚠️  STEP 3: TESTING DEPRECATED FUNCTIONS\n")
cat("----------------------------------------\n")

# Test a few deprecated functions to ensure they still work
test_deprecated_functions <- head(DEPRECATED_FUNCTIONS, 5)
deprecated_test_results <- list()

for (func_name in test_deprecated_functions) {
  tryCatch({
    # Check if function exists and is callable
    func <- get(func_name, envir = asNamespace("engager"))
    if (is.function(func)) {
      deprecated_test_results[[func_name]] <- "OK_WITH_WARNING"
      cat("  ✓", func_name, "- OK (will show deprecation warning)\n")
    } else {
      deprecated_test_results[[func_name]] <- "NOT_FUNCTION"
      cat("  ✗", func_name, "- NOT A FUNCTION\n")
    }
  }, error = function(e) {
    deprecated_test_results[[func_name]] <- paste("ERROR:", e$message)
    cat("  ✗", func_name, "- ERROR:", e$message, "\n")
  })
}

cat("\n✅ DEPRECATED FUNCTIONS TESTED\n\n")

# Step 4: Generate new NAMESPACE content
cat("📝 STEP 4: GENERATING NEW NAMESPACE\n")
cat("-----------------------------------\n")

# Create new NAMESPACE content with only essential functions
new_namespace_content <- c(
  "# Generated by roxygen2: do not edit by hand",
  "",
  "# Essential functions only",
  paste0("export(", ESSENTIAL_FUNCTIONS, ")"),
  "",
  "# Import required functions from other packages",
  "importFrom(magrittr,\"%>%\")",
  "importFrom(stats,aggregate)",
  "importFrom(stats,setNames)",
  "importFrom(utils,read.csv)",
  "importFrom(utils,sessionInfo)",
  "importFrom(utils,str)"
)

# Write new NAMESPACE content
cat("Writing new NAMESPACE with", length(ESSENTIAL_FUNCTIONS), "essential functions...\n")
writeLines(new_namespace_content, "NAMESPACE.new")

cat("  ✓ New NAMESPACE written to NAMESPACE.new\n")
cat("  ✓ Contains", length(ESSENTIAL_FUNCTIONS), "essential functions\n")

# Step 5: Test package loading with new scope
cat("\n🧪 STEP 5: TESTING PACKAGE FUNCTIONALITY\n")
cat("----------------------------------------\n")

# Test that the package still loads correctly
tryCatch({
  # Unload and reload the package
  detach("package:engager", unload = TRUE)
  devtools::load_all()
  
  cat("  ✓ Package loaded successfully with deprecation warnings\n")
  
  # Test that essential functions are available
  available_functions <- ls("package:engager")
  cat("  ✓ Available functions:", length(available_functions), "\n")
  
  # Check that essential functions are still there
  missing_essential <- setdiff(ESSENTIAL_FUNCTIONS, available_functions)
  if (length(missing_essential) == 0) {
    cat("  ✓ All essential functions available\n")
  } else {
    cat("  ✗ Missing essential functions:", paste(missing_essential, collapse = ", "), "\n")
  }
  
}, error = function(e) {
  cat("  ✗ Package loading failed:", e$message, "\n")
})

cat("\n✅ SCOPE REDUCTION IMPLEMENTATION COMPLETE\n")
cat("==========================================\n\n")

# Final summary
cat("📋 FINAL SUMMARY\n")
cat("----------------\n")
cat("Essential functions:", length(ESSENTIAL_FUNCTIONS), "\n")
cat("Deprecated functions:", length(DEPRECATED_FUNCTIONS), "\n")
cat("Scope reduction:", summary$reduction_percentage, "%\n")
cat("New NAMESPACE:", "NAMESPACE.new\n")
cat("\nNext steps:\n")
cat("1. Review NAMESPACE.new\n")
cat("2. Test package thoroughly\n")
cat("3. Update documentation\n")
cat("4. Commit changes\n")
cat("5. Create pull request\n")
