#' Package Data Documentation
#'
#' Zoom transcript data that users provide.
#'
#' The zoomstudentengagement package is designed to work with user-provided data rather than including static datasets.
#' This approach ensures privacy and allows the package to be used with any institutional data without concerns about
#' data sharing or licensing.
#'
#' ## Data Sources
#'
#' Users provide their own data through the following functions:
#' - `load_zoom_transcript()` - Load Zoom transcript files
#' - Internal functions for loading roster data and name matching lookup tables
#' - Internal functions for loading cancelled class information
#'
#' ## Generated Data
#'
#' The package generates various data structures during analysis:
#' - **Analysis Results**: Generated by analysis functions like `analyze_transcripts()`
#' - **Metrics and Reports**: Created by functions like `write_metrics()`
#'
#' ## Example Data Workflow
#'
#' ```r
#' # Load user-provided data
#' transcript <- load_zoom_transcript("my_transcript.vtt")
#'
#' # Generate analysis results
#' results <- analyze_transcripts(transcript)
#'
#' # Export generated data
#' write_metrics(results, "engagement_metrics.csv")
#' ```
#'
#' \code{\link{load_zoom_transcript}} for loading transcript data
#' \code{\link{write_metrics}} for exporting analysis results
#'
#' # This package works with user-provided data
#' # No static datasets are included
#'
#' # Example of typical workflow:
#' # Load your own data
#' # transcript <- load_zoom_transcript("path/to/transcript.vtt")
#' # roster <- load_roster("path/to/roster.csv")
#' #
#' # Analyze and generate results
#' # results <- analyze_transcripts(transcript, roster)
#' #
#' # Export generated data
#' # write_metrics(results, "my_analysis_results.csv")
#'
#' @name data
NULL
