name: Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
    paths:
      - 'scripts/benchmarks/**'
      - 'R/**'

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    
    env:
      BUDGET_1: '10'
      BUDGET_50: '120'
      BUDGET_500: '1200'
    
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/R
            ~/.cache/R
          key: ${{ runner.os }}-benchmarks-${{ hashFiles('.github/workflows/benchmarks.yaml') }}
          restore-keys: |
            ${{ runner.os }}-benchmarks-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev pandoc
        shell: bash

      - name: Install package dependencies
        run: |
          install.packages(c("remotes", "bench"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Run benchmarks
        run: |
          library(bench)
          
          # Check if benchmark script exists
          if (!file.exists("scripts/benchmarks/bench_transcript_pipeline.R")) {
            cat("Benchmark script not found, skipping benchmarks\n")
            exit(0)
          }
          
          # Run performance benchmarks
          source("scripts/benchmarks/bench_transcript_pipeline.R")
          
          # Check if performance is within acceptable limits
          # This would be implemented in the benchmark script
          cat("Benchmarks completed successfully\n")
        shell: Rscript {0}
        timeout-minutes: 15