name: Benchmarks

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
    paths:
      - 'scripts/benchmarks/**'
      - 'R/**'

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    
    env:
      BUDGET_1: '10'
      BUDGET_50: '120'
      BUDGET_500: '1200'
    
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/R
            ~/.cache/R
          key: ${{ runner.os }}-benchmarks-${{ hashFiles('.github/workflows/benchmarks.yaml') }}
          restore-keys: |
            ${{ runner.os }}-benchmarks-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install dependencies
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          install.packages(c("remotes", "bench"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Run benchmarks
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          source("scripts/benchmarks/bench_transcript_pipeline.R")
        shell: Rscript {0}
        timeout-minutes: 30

      - name: Check budget compliance
        run: |
          echo "Benchmark budget check completed"
          echo "Budget 1: $BUDGET_1 seconds"
          echo "Budget 50: $BUDGET_50 seconds" 
          echo "Budget 500: $BUDGET_500 seconds"