name: Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/R
            ~/.cache/R
          key: ${{ runner.os }}-coverage-${{ hashFiles('.github/workflows/coverage.yaml') }}
          restore-keys: |
            ${{ runner.os }}-coverage-

      - name: Install dependencies
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          install.packages(c("remotes", "covr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Generate documentation
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          devtools::document()
        shell: Rscript {0}

      - name: Run coverage
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          covr::codecov(quiet = FALSE)
        shell: Rscript {0}