name: Lint

on:
  pull_request:
    branches: ["*"]

jobs:
  lintr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr
          needs: lint
      - name: Run lintr
        run: |
          Rscript -e "lintr::lint_package(error_on_lint = TRUE)"