# Performance Tests workflow - REPLACED with regression-based approach
# 
# This workflow has been replaced with a sophisticated performance CI system:
# 
# NEW PERFORMANCE CI SYSTEM (Issue #424):
# - performance-regression-guard.yml: Fast PR regression guard
# - performance-weekly-profiling.yml: Comprehensive weekly profiling  
# - update-performance-baseline.yml: Baseline management
# 
# Key improvements:
# 1. Regression-based testing with committed baselines
# 2. Two-tier approach: PR guard + weekly profiling
# 3. Real user workflow testing (not package loading)
# 4. CRAN-safe performance testing
# 5. Memory tracking with GC count and allocation monitoring
# 
# See perf/ directory for implementation details.

# name: Performance Tests
# 
# on:
#   workflow_dispatch:  # Manual trigger only
# 
# jobs:
#   performance:
#     runs-on: ubuntu-latest
#     
#     steps:
#     - uses: actions/checkout@v3
#     
#     - name: Set up R
#       uses: r-lib/actions/setup-r@v2
#       with:
#         r-version: 4.3
#     
#     - name: Install system dependencies
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
#     
#     - name: Install dependencies
#       run: |
#         Rscript -e "install.packages(c('remotes', 'testthat', 'microbenchmark', 'pryr', 'devtools'))"
#     
#     - name: Run benchmarks
#       run: |
#         Rscript scripts/benchmark-ideal-transcripts.R 3 benchmark_results.rds
#     
#     - name: Upload benchmark results
#       uses: actions/upload-artifact@v4
#       with:
#         name: benchmark-results
#         path: benchmark_results.rds