name: Performance Regression Guard

on:
  pull_request:
    branches: [ main, develop, cran-submission-v0.1.0 ]
  workflow_dispatch:

jobs:
  performance-guard:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "bench", "jsonlite"))
          remotes::install_deps(dependencies = TRUE)
      
      - name: Run fast performance tests
        run: |
          Rscript perf/scripts/simple-performance-test.R 5 perf_results.json
      
      - name: Check for performance regressions
        id: regression-check
        run: |
          Rscript perf/scripts/check-performance-regression.R perf_results.json perf/baselines/linux-R-release.json
          echo "regression_detected=$?" >> $GITHUB_OUTPUT
      
      - name: Upload performance results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-results-${{ github.run_number }}
          path: perf_results.json
      
      - name: Comment PR with results
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            if (fs.existsSync('perf_results.json')) {
              const results = JSON.parse(fs.readFileSync('perf_results.json', 'utf8'));
              const regressionDetected = '${{ steps.regression-check.outputs.regression_detected }}' === '1';
              
              const statusIcon = regressionDetected ? '❌' : '✅';
              const statusText = regressionDetected ? 'REGRESSIONS DETECTED' : 'No regressions detected';
              const statusColor = regressionDetected ? 'red' : 'green';
              
              const comment = `## ${statusIcon} Performance Test Results
              
              **Status**: ${statusText}
              **Environment**: ${results.environment.os} - ${results.environment.r_version}
              **Timestamp**: ${results.timestamp}
              
              ### Test Results:
              ${Object.entries(results.tests).map(([test, data]) => 
                `- **${test}**: ${data.time_median_ms.toFixed(1)}ms, ${data.memory_peak_mb.toFixed(1)}MB, ${data.gc_count} GC`
              ).join('\n')}
              
              ${regressionDetected ? `
              ### ⚠️ Performance Regressions
              This PR has performance regressions that exceed the threshold:
              - **Time regression**: +20% threshold
              - **Memory regression**: +30% threshold
              
              **Action Required**: Optimize the code or update the baseline if the regression is acceptable.
              ` : ''}
              
              <details>
              <summary>Raw Results</summary>
              
              \`\`\`json
              ${JSON.stringify(results, null, 2)}
              \`\`\`
              </details>`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
