name: Performance Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  performance:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    strategy:
      matrix:
        r-version: [4.1, 4.3]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
    
    - name: Install dependencies
      run: |
        install.packages(c("remotes", "testthat", "microbenchmark", "pryr"))
        remotes::install_deps(dep = TRUE)
    
    - name: Run performance tests
      run: |
        Rscript -e "devtools::test(filter = 'performance')"
    
    - name: Run benchmarks
      run: |
        if [ -f "scripts/benchmark-ideal-transcripts.R" ]; then
          echo "Running performance benchmarks..."
          timeout 10m Rscript scripts/benchmark-ideal-transcripts.R 3 benchmark_results.rds || echo "Benchmark timed out or failed"
        else
          echo "⚠️  Benchmark script not found, skipping benchmarks"
        fi
    
    - name: Upload benchmark results
      if: always() && hashFiles('benchmark_results.rds') != ''
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results-${{ matrix.r-version }}
        path: benchmark_results.rds
