name: Weekly Performance Profiling

on:
  schedule:
    - cron: '0 2 * * 0'  # Sunday at 2 AM UTC
  workflow_dispatch:

jobs:
  performance-profiling:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "bench", "jsonlite", "profvis"))
          remotes::install_deps(dependencies = TRUE)
      
      - name: Run comprehensive performance profiling
        run: |
          Rscript perf/scripts/performance-profiling.R perf/reports/weekly
      
      - name: Upload profiling reports
        uses: actions/upload-artifact@v4
        with:
          name: performance-profiling-${{ github.run_number }}
          path: perf/reports/weekly/
          retention-days: 30
      
      - name: Create performance summary
        run: |
          echo "## Weekly Performance Profiling Report" > performance_summary.md
          echo "" >> performance_summary.md
          echo "**Date**: $(date)" >> performance_summary.md
          echo "**Environment**: $(uname -s) - R $(R --version | head -1)" >> performance_summary.md
          echo "" >> performance_summary.md
          echo "### Files Generated:" >> performance_summary.md
          find perf/reports/weekly/ -name "*.json" -exec echo "- {}" \; >> performance_summary.md
          find perf/reports/weekly/ -name "*.txt" -exec echo "- {}" \; >> performance_summary.md
          echo "" >> performance_summary.md
          echo "### Latest Results:" >> performance_summary.md
          if [ -f perf/reports/weekly/summary_*.txt ]; then
            cat perf/reports/weekly/summary_*.txt | tail -20 >> performance_summary.md
          fi
      
      - name: Upload performance summary
        uses: actions/upload-artifact@v4
        with:
          name: performance-summary-${{ github.run_number }}
          path: performance_summary.md
          retention-days: 30
      
      - name: Comment on recent PRs with performance insights
        if: github.event_name == 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          script: |
            // Find recent PRs that might benefit from performance insights
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'updated',
              direction: 'desc',
              per_page: 5
            });
            
            if (prs.length > 0) {
              const comment = `## 🔍 Weekly Performance Profiling Complete
              
              Performance profiling has been completed for this week. Check the artifacts for detailed reports.
              
              **Key Metrics Tracked:**
              - Small transcript processing performance
              - Medium transcript processing performance  
              - Large synthetic dataset performance
              - Memory stress testing
              
              **Artifacts Available:**
              - Detailed JSON reports
              - Performance summaries
              - Trend analysis data
              
              This helps ensure the package maintains good performance characteristics over time.`;
              
              // Comment on the most recent PR
              await github.rest.issues.createComment({
                issue_number: prs[0].number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
