name: R-CMD-check

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::roxygen2
          needs: check
      - name: Generate documentation (roxygenise)
        run: |
          Rscript -e "roxygen2::roxygenise()"
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
  guard_no_auto_merge:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Block merge unless labeled allow-merge
        env:
          HAS_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'allow-merge') }}
        run: |
          if [ "$HAS_LABEL" != "true" ]; then
            echo "Blocking merge: add 'allow-merge' label to proceed"
            exit 1
          fi
          echo "Label present; allowing merge"
