name: R-CMD-check

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        r: ['release', 'oldrel-1']
    runs-on: ${{ matrix.os }}
    env:
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
      - name: Install system dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      - name: Install dependencies
        run: |
          install.packages('remotes', repos = 'https://cloud.r-project.org')
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran('rcmdcheck')
          remotes::install_cran('roxygen2')
        shell: Rscript {0}
      - name: Generate documentation (roxygenise)
        run: |
          Rscript -e "roxygen2::roxygenise()"
      - name: Check
        run: |
          rcmdcheck::rcmdcheck(args = c('--no-manual', '--as-cran'))
        shell: Rscript {0}
      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: check-results-${{ matrix.os }}-r${{ matrix.r }}
          path: check
  guard_no_auto_merge:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [R-CMD-check]
    steps:
      - name: Prevent auto-merge on PRs (intentional fail)
        run: |
          echo "Failing guard to prevent auto-merge during refactor"
          exit 1
